/*
 *
 * LiquidityPage constants
 *
 */
export const LIQUIDITYTABS = {
  INDEX: "INDEX",
  ADDLIQUIDITY: "ADDLIQUIDITY",
  REMOVEALIQUIDITY: "REMOVEALIQUIDITY",
  LIQUIDITYPAGE: "LIQUIDITYPAGE",
}

export const DEFAULT_ACTION = 'app/LiquidityPage/DEFAULT_ACTION';
